version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies..."
      - npm install --legacy-peer-deps

  build:
    commands:
      - echo "Building with Vite for mode: $MODE"
      - |
        if [ "$MODE" = "production" ]; then
          echo "VITE_API_URL=$PROD_BACKEND_URL" >> .env
        elif [ "$MODE" = "staging" ]; then
          echo "VITE_API_URL=$TEST_BACKEND_URL" >> .env
        else
          echo "VITE_API_URL=$DEV_BACKEND_URL" >> .env
        fi
      - npm run build

  post_build:
    commands:
      - echo "Syncing to S3..."
      # Added --delete to keep the bucket clean
      - aws s3 sync dist/ s3://$BUCKET_NAME --region af-south-1 --delete

artifacts:
  files: "**/*"
  base-directory: "dist"
  discard-paths: no