import { API_KEY } from "../Constants/Constance";
export const TopRated = `movies/`;
export const originals = `movies/`;
export const action = `movies/`;
export const comedy = `movies/`;
export const horror = `movies/`;
export const Adventure = `movies/`;
export const SciFi = `movies/`;
export const Animated = `movies/`;
export const War = `movies/`;
export const trending = `movies/`;
export const trendingSeries = `movies/`;
export const UpcomingMovies = `movies/`;
